README.md
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=63770485
=> working on feature

README.md
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=63770485
sorry for making a mess in the beginning, but aren't you glad that part is now done
=> Feature 6 again

README.md
it was my turn to do this so i did
=> wrote a message in read me

src/server/db/client.js, src/server/db/seed.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=64971896
=> created tables

package.json, src/client/App.jsx, src/client/components/Account.jsx, src/client/components/CR.jsx, src/client/components/Register.jsx, src/client/components/SingleItem.jsx, src/client/layouts/RootLayout.jsx, src/client/style.css
https://github.com/users/thisiskam/projects/7?pane=issue&itemId=63964718
this is the inital work. we need to train people how to use it
=> routes are set up

package.json, src/server/db/seed.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7?pane=issue&itemId=65160566
=> Feature 33 seed tables

src/server/db/index.js, src/server/db/seed.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=65370607
=> added is_admin and debugged seeding

src/client/components/Login.jsx, src/server/api/index.js, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=65205888
=> userlogin done

src/client/components/Login.jsx, src/server/api/index.js, src/server/api/users.js, src/server/db/index.js, src/server/db/seed.js, src/server/db/users.js, src/server/main.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=65667352
=> store token from login for reuseability

src/client/components/CR.jsx, src/client/style.css
finished with the mainpage for now, will revisit later when i have api routes. going to work on drilled in page for single item now
=> Feature 37 mainpage

src/client/App.jsx, src/client/components/Account.jsx, src/client/components/Login.jsx, src/client/components/Logout.jsx, src/client/layouts/LoginLayout.jsx, src/client/layouts/RootLayout.jsx, src/server/api/index.js, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=65848907
=> so much fun making log in conditionally load account and log out work

src/client/App.jsx, src/client/components/Login.jsx, src/client/components/Register.jsx, src/client/layouts/RootLayout.jsx, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=65423510
=> register works now

src/client/components/CR.jsx, src/client/components/SingleItem.jsx, src/client/style.css
https://github.com/users/thisiskam/projects/7?pane=issue&itemId=65846730
=> Feature 54 initialize drilledin

src/server/api/index.js, src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66009860
=> created add items route

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66220667
=> get single item route

src/server/db/seed.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66234147
=> constraint is now in place

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66241834
=> post items route

src/server/api/index.js, src/server/api/reviews.js, src/server/db/reviews.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66232838
=> commit because

src/server/api/items.js, src/server/db/items.js, src/server/db/seed.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66245967
=> update item route

src/client/App.jsx, src/client/components/Login.jsx, src/client/components/Register.jsx, src/client/style.css
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66407167
=> CSS is working

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66976623
=> did nothing

src/client/components/AllUsers.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66222537
=> no changes

src/client/components/AllUsers.jsx, src/client/components/SingleItem.jsx, src/client/style.css
some styling in css
calls api to get all reviews and maps through them
calls api to get all users temporarily so i can display usernames with the reviews
logged in users can see a leave a review and leave a comment button, those buttons take the user to forms to do so
=> Feature 54 api calls

src/client/components/CR.jsx, src/server/db/client.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66404668
your code wont work unless you add the updated stuff and pull from main
=> done with this

src/server/api/index.js, src/server/api/items.js, src/server/api/users.js, src/server/db/items.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66246348
=> post-reviews route with hardcoded user_id

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66246360
=> update-review route

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66246376
=> delete-review route

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66247727
=> get all comments route created

src/client/components/Account.jsx, src/client/components/Login.jsx, src/client/components/Logout.jsx, src/client/components/Register.jsx, src/server/api/index.js, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=67155847
=> pushing a nothing burger with no changes and many

src/server/api/items.js, src/server/db/items.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66247819
=> delete comment route created

src/client/components/SingleItem.jsx, src/client/style.css
finished get comments on the drilled in page
=> Feature 113 comments

src/server/api/index.js
not a bug but Kam needs this and yesterday's changes broke it shrug
=> fixing working stuff

src/server/api/items.js, src/server/db/items.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66243603
=> logged in and admin middleware complete

src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66220151
=> get me route created

src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1
=> get my reviews route

src/client/components/Account.jsx
one of many 
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=63773572
=> small checkin

src/client/components/CR.jsx, src/client/components/Login.jsx, src/client/components/Logout.jsx, src/server/api/index.js, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=63773572
=> omg shoot me

src/client/components/CR.jsx, src/client/components/SingleItem.jsx, src/client/style.css
finished all the drilled page stylings and functions, now i just need the routes. also made some changes to the home page, adding comments and trying a function to find user. routes to post reviews and comments and edit and delete them still dont work for me, idk why
=> single page, css and CR

src/client/components/Account.jsx, src/server/api/index.js, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68149212
=> me routes YIPPYgit add .

src/client/App.jsx, src/client/components/AddItem.jsx, src/client/components/AdminItems.jsx, src/client/components/AllUsers.css
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68160211
=> doing item

src/client/components/Account.jsx, src/server/db/client.js, src/server/db/seed.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68177298
=> i like joins

src/client/components/CR.jsx, src/client/components/SingleItem.jsx, src/server/api/items.js, src/server/db/items.js
all the routes on the single page are up and running, edit/post/delete on all comments reviews and items. fixed a route on the back end so the admin can also change category id
=> Feature 115 edit delete

src/client/components/Account.jsx, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68177298
=> donsies by kb

src/client/App.jsx, src/client/components/AddUser.jsx, src/client/components/AllUsers.css, src/client/components/AllUsers.jsx, src/client/components/Register.jsx, src/client/style.css, src/server/api/users.js, src/server/db/seed.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66227929
=> create a user as an admin is so finito

src/client/components/AddItem.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68335217
=> Mark sayed this is important

src/client/App.jsx, src/client/components/AddUser.jsx, src/client/components/AllUsers.css, src/client/components/AllUsers.jsx, src/client/components/UpdateUser.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=66227929
more to come
=> stubbed updateUser

package.json, src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68423742
=> update-user backend route

src/client/components/SingleItem.jsx, src/client/style.css
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68560499
=> fix button width and capitalizing button names

package.json, src/client/components/Account.css, src/client/components/Account.jsx, src/client/components/SingleItem.jsx, src/client/style.css
the account page has been styled and now works.
=> Feature 7 account style

src/server/api/users.js, src/server/db/users.js
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68571014
=> backend delete user route created

src/client/components/UpdateUser.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68560499
=> need Kameron help

src/client/components/AllUsers.css, src/client/components/UpdateUser.jsx
can edit and delete a user now
=> Feature 74 admin edit user

src/client/components/CR.jsx, src/client/style.css
https://github.com/users/thisiskam/projects/7/views/1
=> css is so fun

src/client/components/SingleItem.jsx, src/client/style.css
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68579746
=> changed two button colors

src/client/components/AddUser.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68591581
=> secured add users

src/client/components/AllUsers.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68594784
=> secured all users

src/client/components/AddItem.jsx, src/client/components/AdminItems.jsx
https://github.com/users/thisiskam/projects/7/views/1?pane=issue&itemId=68579855
=> thank you Kameron and Katie

src/client/components/AllUsers.jsx
fixed on e quick thing with the all users page
=> fixed a bug
